# Site settings
title: SNMS Lab
description: Academic webpage of SNMS Lab
baseurl: "/snms-lab-web/"
url: "https://xietian1.github.io"

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
    Security, Networking, and Mobile Systems Research (SNMS) Laboratory<br/>
    Department of Computer Science and Engineering<br/>
    Michigan State University

# location: >
#   California Institute of Technology<br/>
#   1200 E California Blvd<br/>
#   Pasadena, CA 91125


# Pages shown in navbar
nav_pages:
  - name: news
  # - name: about
  - name: publications
  # - name: talks
  - name: research
  # - name: software
  - name: team
  # - name: teaching

include:
  - .htaccess
  - _pages
  - _projects

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


# plugins: ['jekyll/scholar']

# scholar:

#   last_name: Doe
#   first_name: [John]

#   style: citesty
#   locale: en

#   source: /assets/
#   bibliography: ref.bib
#   bibliography_template: bibtemplate
#   sort_by: year, month
#   order: descending

#   replace_strings: true
#   join_strings: true

#   details_dir: bibliography
#   details_layout: bibtex.html
#   details_link: Details

#   query: "@*"

#   bibliography_list_attributes:
#     reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
